USE WAREHOUSE CATFISH_QUERY_WH;
USE DATABASE USER_DB_CATFISH;
-- Schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS MODEL;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- RAW Layer: Ingested daily bars
CREATE TABLE IF NOT EXISTS RAW.STOCK_PRICES (
  SYMBOL           STRING        NOT NULL,
  TS               TIMESTAMP_NTZ NOT NULL,
  OPEN             FLOAT,
  HIGH             FLOAT,
  LOW              FLOAT,
  CLOSE            FLOAT,
  ADJ_CLOSE        FLOAT,
  VOLUME           NUMBER(38,0),
  LOAD_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_STOCK_PRICES PRIMARY KEY (SYMBOL, TS)
);

-- MODEL Layer: Forecast outputs (one row per date per symbol)
CREATE TABLE IF NOT EXISTS MODEL.FORECASTS (
  SYMBOL           STRING        NOT NULL,
  TS               DATE          NOT NULL,
  PREDICTED_CLOSE  FLOAT         NOT NULL,
  MODEL_NAME       STRING        NOT NULL,
  TRAINED_AT       TIMESTAMP_NTZ NOT NULL,
  HORIZON_D        NUMBER(5,0)   NOT NULL,
  LOAD_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FORECASTS PRIMARY KEY (SYMBOL, TS, MODEL_NAME)
);

-- ANALYTICS Layer: Union of actuals + forecasts (latest partition wins on overlap)
CREATE TABLE IF NOT EXISTS ANALYTICS.FINAL_PRICES_FORECAST (
  SYMBOL           STRING        NOT NULL,
  TS               DATE          NOT NULL,
  CLOSE            FLOAT,
  SOURCE           STRING        NOT NULL,  -- 'ACTUAL' or 'FORECAST'
  MODEL_NAME       STRING,                 -- null for ACTUAL
  LOAD_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FINAL PRIMARY KEY (SYMBOL, TS, SOURCE)
);